# config/zed_yaml
# Parameters for Stereolabs ZED camera
---

zed:
    zed_node:
        ros__parameters:
            general:
                camera_model: 0 # `0`: ZED, `1`: ZEDM
                zed_id: 0
            depth:
                min_depth: 0.3  # Min: 0.3, Max: 3.0
                max_depth: 20. #Dynamic
            tracking:
                initial_tracking_pose: [0.0,0.0,0.0, 0.0,0.0,0.0]               # [X, Y, Z, R, P, Y]
