# config/zed_yaml
# Parameters for Stereolabs ZED camera
---

zed:
    zed_node:
        ros__parameters:
            general:
                camera_model: 0 # `0`: ZED, `1`: ZEDM
            depth:
                max_depth: 20. #Dynamic
