# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---

zed:
    zed_node:
        ros__parameters:
            general:
                camera_model: 1                 # `0`: ZED, `1`: ZEDM
            depth:
                min_depth: 0.1                  # Min: 0.1, Max: 3.0
                max_depth: 10.                  # Dynamic
            imu:
                imu_frame: 'zed_imu_link'
                imu_topic_root: 'imu'
                imu_topic: 'data'
                imu_raw_topic: 'data_raw'
                imu_pub_rate: 100.0
                imu_sync_frame: false
