# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---

zed:
    zed_node:
        ros__parameters:
            general:
                camera_model:       1                 # `0`: ZED, `1`: ZEDM
            depth:
                min_depth:          0.1               # Min: 0.1, Max: 3.0
                max_depth:          10.               # Dynamic
            imu:
                imu_frame:          'zed_imu_link'
                imu_topic_root:     'imu'
                imu_topic:          'data'
                imu_raw_topic:      'data_raw'
                imu_pub_rate:       100.0
                imu_sync_frame:     false
                qos_history:        1                # '0': KEEP_LAST - '1': KEEP_ALL
                qos_depth:          5                # Queue size if using KEEP_LAST
                qos_reliability:    1                 # '0': BEST_EFFORT - '1': RELIABLE
                qos_durability:     1                 # '0': TRANSIENT_LOCAL - '1': VOLATILE
